# Generated by Django 5.1.4 on 2025-01-11 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="role",
            field=models.CharField(default="Customer", max_length=20),
        ),
        migrations.AddField(
            model_name="deliverypersonnel",
            name="role",
            field=models.CharField(default="Delivery_personnel", max_length=20),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="role",
            field=models.CharField(default="Restaurent_owner", max_length=20),
        ),
    ]
