# Generated by Django 5.1.4 on 2025-01-22 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_customer_role_deliverypersonnel_role_restaurant_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(default="street", max_length=255),
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="address",
        ),
        migrations.AddField(
            model_name="customer",
            name="city",
            field=models.CharField(default="city", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="country",
            field=models.CharField(default="country", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="postal_code",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AddField(
            model_name="customer",
            name="state",
            field=models.CharField(default="state", max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="street",
            field=models.CharField(default="street", max_length=255),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="city",
            field=models.CharField(default="city", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="country",
            field=models.CharField(default="country", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="postal_code",
            field=models.CharField(default="000000", max_length=10),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="state",
            field=models.CharField(default="state", max_length=100),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="street",
            field=models.CharField(default="street", max_length=255),
        ),
        migrations.DeleteModel(
            name="Address",
        ),
    ]
