# Generated by Django 5.1.4 on 2025-01-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_order_delivery_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deliverypersonnel",
            name="vehicle_registration",
        ),
        migrations.AddField(
            model_name="deliverypersonnel",
            name="vehicle_registration_certificate",
            field=models.CharField(
                default="vehicle_registration_certificate", max_length=50, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="deliverypersonnel",
            name="account_number",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="deliverypersonnel",
            name="driving_license",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="deliverypersonnel",
            name="pan_card",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
