# Generated by Django 5.1.4 on 2025-01-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_deliverypersonnel_vehicle_registration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverypersonnel",
            name="vehicle_registration_certificate",
            field=models.CharField(
                default="AXYKR7410852963", max_length=50, unique=True
            ),
        ),
    ]
