# Generated by Django 5.1.4 on 2025-01-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_customer_user_alter_deliverypersonnel_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="category",
        ),
    ]
