# Generated by Django 5.1.4 on 2025-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_ingredient_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant",
            name="is_open",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("close", "Close")],
                default="open",
                max_length=5,
            ),
        ),
    ]
