# Generated by Django 5.1.4 on 2025-01-26 12:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_remove_restaurant_is_open_restaurant_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone1", models.CharField(max_length=15)),
                ("phone2", models.CharField(blank=True, max_length=15, null=True)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "number_of_persons",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="core.restaurant",
                    ),
                ),
            ],
        ),
    ]
