# Generated by Django 5.1.4 on 2025-01-27 13:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_favoritefooditem_favoriterestaurant"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="favoritefooditem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="favoriterestaurant",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="favoritefooditem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="favoriterestaurant",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
