# Generated by Django 5.1.4 on 2025-01-28 16:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_favoritefooditem_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurantvisit",
            options={"ordering": ["-visited_at"]},
        ),
        migrations.RemoveField(
            model_name="customer",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="country",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="postal_code",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="state",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="street",
        ),
        migrations.AddField(
            model_name="restaurant",
            name="dining_capacity",
            field=models.PositiveIntegerField(
                default=50, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="restaurant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="core.restaurant",
            ),
        ),
        migrations.AlterField(
            model_name="restaurantvisit",
            name="visited_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=10)),
                ("country", models.CharField(max_length=100)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to="core.customer",
                    ),
                ),
            ],
        ),
    ]
