# Generated by Django 5.1.4 on 2025-02-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_reservation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("prepaid", "Prepaid"), ("cod", "Cash on Delivery")],
                default="prepaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=10,
            ),
        ),
    ]
