# Generated by Django 5.1.4 on 2025-02-21 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("preparing", "Preparing"),
                    ("out_for_delivery", "Out for Delivery"),
                    ("delivered", "Delivered"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("ready_for_pickup", "Ready for Pickup"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
