# Generated by Django 5.1.4 on 2025-02-27 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_acceptance",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
