# Generated by Django 5.1.4 on 2025-03-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_order_delivery_acceptance"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("order", "Order Related"),
                    ("promotional", "Promotional"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("new_order", "New Order"),
                    ("new_reservation", "New Reservation"),
                    ("order_canceled", "Order Canceled"),
                    ("order_status", "Order Status Update"),
                    ("reservation_status", "Reservation Status"),
                    ("new_delivery", "New Delivery Assignment"),
                    ("order_ready", "Order Ready for Pickup"),
                    ("delivery_canceled", "Delivery Canceled"),
                    ("promotional", "Promotional Event"),
                ],
                max_length=20,
            ),
        ),
    ]
