# Generated by Django 5.1.4 on 2025-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_adminpaymentdetails_event_is_promotional_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminpaymentdetails",
            options={
                "verbose_name": "Admin Payment Detail",
                "verbose_name_plural": "Admin Payment Details",
            },
        ),
        migrations.AddField(
            model_name="deliverypersonnel",
            name="average_rating",
            field=models.FloatField(default=0.0),
        ),
    ]
